org.gradle.jvmargs=-Xmx1100M -XX:MaxMetaspaceSize=512M -XX:+UseSerialGC
org.gradle.workers.max=1
kotlin.daemon.jvmargs=-Xmx900M
kotlin.compiler.execution.strategy=in-process
android.useAndroidX=true
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
org.gradle.daemon=true
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
org.gradle.daemon=false
org.gradle.java.installations.paths=/home/z/jdk-21.0.12.1+1
org.gradle.caching=false
