import 'dart:convert';
import 'dart:typed_data';

/// Subtitle text encodings (v1.10.0 Arabic toolkit).
///
/// Legacy Arabic subtitle files (.srt from old sites) are almost always
/// Windows-1256 or ISO-8859-6 — decoded as raw bytes by mpv they show up
/// as mojibake (Ø£Ø­Ù…Ø¯ or ¿¿¿). Dart ships no single-byte Arabic codec,
/// so the tables below (generated from the WHATWG/IANA mappings) do the
/// conversion natively, plus a scoring heuristic that picks the right one
/// automatically.
enum SubtitleEncoding {
  auto('auto'),
  utf8('utf8'),
  windows1256('windows1256'),
  iso8859_6('iso8859_6'),
  windows1252('windows1252');

  const SubtitleEncoding(this.id);

  /// Stable persistence/UI token.
  final String id;

  static SubtitleEncoding fromId(String? id) => SubtitleEncoding.values
      .firstWhere((e) => e.id == id, orElse: () => SubtitleEncoding.auto);
}

/// Pure, dependency-free charset conversion + detection.
class SubtitleCharset {
  SubtitleCharset._();

  // ---- tables: byte 0x80..0xFF -> code point (0 = undefined) -------------
  // Generated by scripts/gen_charset_tables.py from Python's codec package
  // (which follows the WHATWG encoding standard).

  static const List<int> _cp1256High = <int>[
    0x20AC, 0x067E, 0x201A, 0x0192, 0x201E, 0x2026, 0x2020, 0x2021,
    0x02C6, 0x2030, 0x0679, 0x2039, 0x0152, 0x0686, 0x0698, 0x0688,
    0x06AF, 0x2018, 0x2019, 0x201C, 0x201D, 0x2022, 0x2013, 0x2014,
    0x06A9, 0x2122, 0x0691, 0x203A, 0x0153, 0x200C, 0x200D, 0x06BA,
    0x00A0, 0x060C, 0x00A2, 0x00A3, 0x00A4, 0x00A5, 0x00A6, 0x00A7,
    0x00A8, 0x00A9, 0x06BE, 0x00AB, 0x00AC, 0x00AD, 0x00AE, 0x00AF,
    0x00B0, 0x00B1, 0x00B2, 0x00B3, 0x00B4, 0x00B5, 0x00B6, 0x00B7,
    0x00B8, 0x00B9, 0x061B, 0x00BB, 0x00BC, 0x00BD, 0x00BE, 0x061F,
    0x06C1, 0x0621, 0x0622, 0x0623, 0x0624, 0x0625, 0x0626, 0x0627,
    0x0628, 0x0629, 0x062A, 0x062B, 0x062C, 0x062D, 0x062E, 0x062F,
    0x0630, 0x0631, 0x0632, 0x0633, 0x0634, 0x0635, 0x0636, 0x00D7,
    0x0637, 0x0638, 0x0639, 0x063A, 0x0640, 0x0641, 0x0642, 0x0643,
    0x00E0, 0x0644, 0x00E2, 0x0645, 0x0646, 0x0647, 0x0648, 0x00E7,
    0x00E8, 0x00E9, 0x00EA, 0x00EB, 0x0649, 0x064A, 0x00EE, 0x00EF,
    0x064B, 0x064C, 0x064D, 0x064E, 0x00F4, 0x064F, 0x0650, 0x00F7,
    0x0651, 0x00F9, 0x0652, 0x00FB, 0x00FC, 0x200E, 0x200F, 0x06D2,
  ];

  static const List<int> _iso8859_6High = <int>[
    0x0080, 0x0081, 0x0082, 0x0083, 0x0084, 0x0085, 0x0086, 0x0087,
    0x0088, 0x0089, 0x008A, 0x008B, 0x008C, 0x008D, 0x008E, 0x008F,
    0x0090, 0x0091, 0x0092, 0x0093, 0x0094, 0x0095, 0x0096, 0x0097,
    0x0098, 0x0099, 0x009A, 0x009B, 0x009C, 0x009D, 0x009E, 0x009F,
    0x00A0, 0x0000, 0x0000, 0x0000, 0x00A4, 0x0000, 0x0000, 0x0000,
    0x0000, 0x0000, 0x0000, 0x0000, 0x060C, 0x00AD, 0x0000, 0x0000,
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    0x0000, 0x0000, 0x0000, 0x061B, 0x0000, 0x0000, 0x0000, 0x061F,
    0x0000, 0x0621, 0x0622, 0x0623, 0x0624, 0x0625, 0x0626, 0x0627,
    0x0628, 0x0629, 0x062A, 0x062B, 0x062C, 0x062D, 0x062E, 0x062F,
    0x0630, 0x0631, 0x0632, 0x0633, 0x0634, 0x0635, 0x0636, 0x0637,
    0x0638, 0x0639, 0x063A, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    0x0640, 0x0641, 0x0642, 0x0643, 0x0644, 0x0645, 0x0646, 0x0647,
    0x0648, 0x0649, 0x064A, 0x064B, 0x064C, 0x064D, 0x064E, 0x064F,
    0x0650, 0x0651, 0x0652, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
  ];

  /// Latin-1: bytes 0x80..0xFF map to U+0080..U+00FF directly.
  static String _decodeLatin1(List<int> bytes) =>
      String.fromCharCodes(bytes);

  /// Decodes a single-byte-charset payload via [table] (0x00..0x7F are
  /// ASCII in all of them). Undefined bytes become U+FFFD.
  static String _decodeHigh(List<int> bytes, List<int> table) {
    // NOTE: StringBuffer's constructor takes initial CONTENT, not a
    // capacity — never pass the byte count there.
    final out = StringBuffer();
    for (final b in bytes) {
      if (b < 0x80) {
        out.writeCharCode(b);
      } else {
        final cp = table[b - 0x80];
        out.writeCharCode(cp == 0 ? 0xFFFD : cp);
      }
    }
    return out.toString();
  }

  // ---- detection ---------------------------------------------------------

  /// UTF-8 BOM.
  static const List<int> _bom = [0xEF, 0xBB, 0xBF];

  static bool _hasUtf8Bom(List<int> b) =>
      b.length >= 3 && b[0] == _bom[0] && b[1] == _bom[1] && b[2] == _bom[2];

  /// Strict UTF-8 validation (no BOM needed). Dart's utf8.decode throws
  /// on invalid input, which is exactly the strictness detection needs.
  static bool _isStrictUtf8(List<int> bytes) {
    try {
      utf8.decode(bytes);
      return true;
    } on FormatException {
      return false;
    }
  }

  /// True when [ch] is an Arabic-block letter (incl. Tatweel/punct that
  /// only occur in Arabic text).
  static bool isArabicChar(int ch) =>
      (ch >= 0x0600 && ch <= 0x06FF) ||
      (ch >= 0x0750 && ch <= 0x077F) ||
      (ch >= 0xFB50 && ch <= 0xFDFF) ||
      (ch >= 0xFE70 && ch <= 0xFEFF);

  /// Approximate Arabic letter frequencies (per 100 letters, rounded from
  /// public corpus statistics). The KEY insight for charset detection: an
  /// Arabic file decoded with the WRONG Arabic charset still yields
  /// Arabic-looking text, but common letters (ا ل م ن) land on rare ones
  /// (ٌ خ ة). Average frequency therefore separates the two decodes.
  static const Map<int, double> _letterWeight = {
    0x0627: 12.5, // ا alef
    0x0644: 10.5, // lam ل
    0x064A: 8.2, // ي ya
    0x0645: 7.5, // م meem
    0x0646: 7.3, // ن noon
    0x0648: 6.3, // و waw
    0x062A: 5.0, // ت ta
    0x0631: 4.7, // ر ra
    0x0647: 4.5, // ه ha
    0x0639: 4.2, // ع ain
    0x0628: 4.0, // ب ba
    0x0643: 3.9, // ك kaf
    0x0633: 3.4, // س seen
    0x0641: 3.3, // ف fa
    0x0642: 2.9, // ق qaf
    0x062F: 2.6, // د dal
    0x0623: 2.5, // أ hamza-on-alef
    0x062D: 2.4, // ح hha
    0x062C: 2.2, // ج jeem
    0x0629: 2.0, // ة ta-marbuta
    0x0634: 1.6, // ش sheen
    0x0637: 1.5, // ط ta
    0x0635: 1.4, // ص sad
    0x0632: 1.3, // ز zay
    0x062E: 1.2, // خ kha
    0x063A: 0.9, // غ ghain
    0x0636: 0.8, // ض dad
    0x062B: 0.7, // ث tha
    0x0630: 0.7, // ذ dhal
    0x0638: 0.4, // ظ dha
    0x0622: 1.5, // آ madda-alef
    0x0625: 1.5, // إ alef-hamza-below
    0x0649: 1.0, // ى alef-maksura
    0x0621: 0.3, // ء standalone hamza
  };

  /// Mean frequency weight of the Arabic letters in [text], minus a
  /// penalty for replacement characters. 0 when there are no Arabic
  /// letters (Latin candidates therefore never win by accident).
  static double _scoreArabic(String text) {
    var arabic = 0;
    var weight = 0.0;
    var bad = 0;
    for (final r in text.runes) {
      if (r == 0xFFFD) {
        bad++;
        continue;
      }
      final w = _letterWeight[r];
      if (w != null) {
        arabic++;
        weight += w;
      }
    }
    if (arabic == 0) return 0;
    final mean = weight / arabic;
    final badRatio = bad / (bad + arabic);
    return mean - badRatio * 10;
  }

  /// Picks the encoding for [bytes]:
  /// 1. UTF-8 BOM or strict-valid UTF-8 → utf8 (superset: any ASCII file
  ///    also validates, which is correct — ASCII is the same everywhere).
  /// 2. Otherwise decode with the three candidate charsets and score each
  ///    by MEAN ARABIC LETTER FREQUENCY (see [_letterWeight]): the correct
  ///    charset turns the text into common letters, while the wrong Arabic
  ///    charset maps common letters onto rare ones. Replacement characters
  ///    (bytes undefined in a candidate) are penalized per occurrence.
  ///    Pure Latin text scores 0 on every candidate → windows1252.
  ///    Never throws.
  static SubtitleEncoding detect(List<int> bytes) {
    final b = bytes is Uint8List ? bytes : Uint8List.fromList(bytes);
    if (b.isEmpty) return SubtitleEncoding.utf8;
    if (_hasUtf8Bom(b)) return SubtitleEncoding.utf8;
    if (_isStrictUtf8(b)) return SubtitleEncoding.utf8;

    final s1256 = _scoreArabic(_decodeHigh(b, _cp1256High));
    final sIso = _scoreArabic(_decodeHigh(b, _iso8859_6High));
    final sLatin = _scoreArabic(_decodeLatin1(b));

    if (s1256 < _arabicThreshold &&
        sIso < _arabicThreshold &&
        sLatin < _arabicThreshold) {
      // No candidate looks like real Arabic prose → legacy Latin text.
      return SubtitleEncoding.windows1252;
    }
    // windows-1256 is overwhelmingly the most common encoding for legacy
    // Arabic .srt files, so ties go to it.
    if (s1256 >= sIso && s1256 >= sLatin) return SubtitleEncoding.windows1256;
    if (sIso >= sLatin) return SubtitleEncoding.iso8859_6;
    return SubtitleEncoding.windows1252;
  }

  /// Real Arabic prose scores ~6-7.5 on the frequency scale; stray accented
  /// Latin letters misread through an Arabic table peak around ~1.0. The
  /// midpoint is a safe cut.
  static const double _arabicThreshold = 2.5;

  /// Decodes subtitle bytes with an explicit or auto-detected encoding.
  /// Never throws: undecodable input degrades to replacement characters.
  static String decode(List<int> bytes, {SubtitleEncoding? encoding}) {
    final enc = encoding ?? SubtitleEncoding.auto;
    final b = bytes is Uint8List ? bytes : Uint8List.fromList(bytes);
    switch (enc) {
      case SubtitleEncoding.utf8:
        return utf8.decode(b, allowMalformed: true);
      case SubtitleEncoding.windows1256:
        return _decodeHigh(b, _cp1256High);
      case SubtitleEncoding.iso8859_6:
        return _decodeHigh(b, _iso8859_6High);
      case SubtitleEncoding.windows1252:
        return _decodeLatin1(b);
      case SubtitleEncoding.auto:
        final detected = detect(b);
        if (detected == SubtitleEncoding.auto) {
          return utf8.decode(b, allowMalformed: true);
        }
        return decode(b, encoding: detected);
    }
  }
}
