import 'dart:io';

import 'package:path_provider/path_provider.dart';
import 'package:youtube_explode_dart/youtube_explode_dart.dart';

import '../../core/utils/logger.dart';
import '../smart/intel_v2.dart' show CaptionCue, SrtBuilder;

/// One selectable caption track of a YouTube video.
class CaptionTrackInfo {
  const CaptionTrackInfo({
    required this.languageCode,
    required this.languageName,
    required this.isAutoGenerated,
  });

  final String languageCode;
  final String languageName;
  final bool isAutoGenerated;

  String get label => isAutoGenerated
      ? '$languageName (${autoTag})'
      : languageName;
  static const autoTag = 'auto';
}

/// YouTube automatic subtitles (v1.12.0): lists the closed-caption tracks
/// of a video, downloads the best one (Arabic → English → first
/// available), converts it to SRT with the pure [SrtBuilder] and stores
/// it under the app cache so the existing external-subtitle pipeline
/// (charset normalization + mpv sub-add) can load it like any local file.
///
/// Every failure returns null — captions are a bonus, never a blocker.
class YouTubeCaptions {
  YouTubeCaptions._();
  static final YouTubeCaptions instance = YouTubeCaptions._();

  YoutubeExplode? _yt;
  YoutubeExplode get _cap => _yt ??= YoutubeExplode();

  /// Lists available tracks (may be empty — many videos have none).
  Future<List<CaptionTrackInfo>> listTracks(String videoId) async {
    try {
      final manifest = await _cap.videos.closedCaptions
          .getManifest(videoId)
          .timeout(const Duration(seconds: 10));
      return manifest.tracks
          .map((t) => CaptionTrackInfo(
                languageCode: t.language.code,
                languageName: t.language.name,
                isAutoGenerated: t.isAutoGenerated,
              ))
          .toList();
    } catch (e, s) {
      AppLogger.instance.warning('captions', 'listTracks failed: $e');
      AppLogger.instance.error('captions', 'listTracks error', e, s);
      return const [];
    }
  }

  /// Picks the best track: exact Arabic → Arabic-family → English → any.
  static CaptionTrackInfo? pickBest(List<CaptionTrackInfo> tracks) {
    if (tracks.isEmpty) return null;
    CaptionTrackInfo? fallback;
    for (final t in tracks) {
      final l = t.languageCode.toLowerCase();
      if (l == 'ar') return t;
      if (l.startsWith('ar')) fallback ??= t;
    }
    for (final t in tracks) {
      final l = t.languageCode.toLowerCase();
      if (l.startsWith('en')) return t;
    }
    return fallback ?? tracks.first;
  }

  /// Downloads + converts + saves the best caption track. Returns the
  /// SRT file path, or null on any failure.
  Future<String?> fetchSrt(
    String videoId, {
    CaptionTrackInfo? preferred,
    Duration timeout = const Duration(seconds: 12),
  }) async {
    try {
      final manifest = await _cap.videos.closedCaptions
          .getManifest(videoId)
          .timeout(timeout);
      final tracks = manifest.tracks.toList();
      if (tracks.isEmpty) return null;

      ClosedCaptionTrackInfo chosen;
      if (preferred != null) {
        chosen = tracks.firstWhere(
          (t) =>
              t.language.code.toLowerCase() ==
                  preferred.languageCode.toLowerCase() &&
              t.isAutoGenerated == preferred.isAutoGenerated,
          orElse: () => tracks.first,
        );
      } else {
        final best = pickBest(tracks
            .map((t) => CaptionTrackInfo(
                  languageCode: t.language.code,
                  languageName: t.language.name,
                  isAutoGenerated: t.isAutoGenerated,
                ))
            .toList());
        if (best == null) return null;
        chosen = tracks.firstWhere(
          (t) =>
              t.language.code.toLowerCase() == best.languageCode.toLowerCase() &&
              t.isAutoGenerated == best.isAutoGenerated,
          orElse: () => tracks.first,
        );
      }

      final track = await _cap.videos.closedCaptions
          .get(chosen)
          .timeout(timeout);
      final cues = track.captions
          .map((c) => CaptionCue(
                startMs: c.offset.inMilliseconds,
                durationMs: c.duration.inMilliseconds,
                text: c.text,
              ))
          .toList();
      if (cues.isEmpty) return null;

      final srt = SrtBuilder.build(cues);
      final dir = await _subtitleDir();
      final lang = chosen.language.code.replaceAll(RegExp(r'[^a-z0-9-]', caseSensitive: false), '');
      final auto = chosen.isAutoGenerated ? '_auto' : '';
      final file = File('${dir.path}/yt_$videoId${auto}_$lang.srt');
      await file.writeAsString(srt, flush: true);
      AppLogger.instance
          .info('captions', 'saved ${cues.length} cues → ${file.path}');
      return file.path;
    } catch (e, s) {
      AppLogger.instance.error('captions', 'fetchSrt $videoId failed', e, s);
      return null;
    }
  }

  Future<Directory> _subtitleDir() async {
    final base = await getTemporaryDirectory();
    final dir = Directory('${base.path}/subtitles');
    if (!dir.existsSync()) dir.createSync(recursive: true);
    return dir;
  }
}
